name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # dispara o deploy quando fizer push na branch main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm install
          npm run build

      - name: Deploy to GitHub Pages
        uses: actions/configure-pages@v3

      - name: Upload build artifacts
        uses: actions/upload-pages-artifact@v1
        with:
          path: './public/build'  # pasta onde o build é gerado

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
